server:
  port: 5337

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/barter_bay
    username: postgres
    password: postgres

  mail:
    username: BarterBay@gmail.com
    password: SuperProductionPassword

# ===================================================================
# Barter Bay Application specific properties
# ===================================================================

jwt:
  secret: Y # to be defined after JWT implementation

