server:
  port: 5337

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://aai6k6jf4f51rw.cpe4kaa3farp.us-east-1.rds.amazonaws.com:5432/ebdb
    username: Alexandro
    password: G_it_is_a_GramoTa

  mail:
    username: BarterBay@gmail.com
    password: SuperProductionPassword

# ===================================================================
# Barter Bay Application specific properties
# ===================================================================

jwt:
  secret: Y # to be defined after JWT implementation

