server:
  port: 3111

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/barter-bay-dev
    username: postgres
    password: kolirzet09

  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: '250'

  mail:
    username: BarterBay.localhost@gmail.com
    password: ${EMAIL_CLIENT_DEV_PASSWORD}

# ===================================================================
# Barter Bay Application specific properties
# ===================================================================

jwt:
  secret: Y # to be defined after JWT implementation
