server:
  port: 5337

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    username: BarterBay@gmail.com
    password: ${EMAIL_CLIENT_PROD_PASSWORD}

# ===================================================================
# Barter Bay Application specific properties
# ===================================================================

jwt:
  secret: Y # to be defined after JWT implementation
