# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#
# Empty values will be passed from the container environment
# variables at runtime.
#
# ===================================================================

server:
  servlet:
    context-path: /v1/bb

spring:
  profiles:
    default: prod

  application:
    name: BarterBay

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      accept_float_as_int: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    hikari:
      poolName: Hikari
      maximumPoolSize: 5
      minimum-idle: 1
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 30000
      auto-commit: true
      maxLifetime: 900000

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml

  main:
    allow-bean-definition-overriding: true

  task:
    execution:
      thread-name-prefix: barter-bay-api-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: barter-bay-api-scheduling-
      pool:
        size: 2
  thymeleaf:
    cache: true
    mode: HTML

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          connectiontimeout: 20000  # 20 seconds
          timeout: 20000            # 20 seconds
          writetimeout: 20000       # 20 seconds
          auth: true
          starttls:
            enable: true


# ===================================================================
# Barter Bay Application specific properties
# ===================================================================

compliment-telegram-bot:
  name: ${COMPLIMENT_BOT_NAME}
  token: ${COMPLIMENT_BOT_TOKEN}

compliment-stasya-telegram-bot:
  name: ${COMPLIMENT_STASYA_BOT_NAME}
  token: ${COMPLIMENT_STASYA_BOT_TOKEN}

prediction-telegram-bot:
  name: ${PREDICTION_BOT_NAME}
  token: ${PREDICTION_BOT_TOKEN}

random-compliment-api:
  url: https://complimentr.com/api

horoscope-api:
  url: https://aztro.sameerkumar.website

yes-or-no-api:
  url: https://www.goddessflight.com/magiceightballresponses.txt

aws:
  all-bucket-names: bb-good-photos,barter-bay-app-packages
  s3:
    region:
      virginia: us-east-1
      paris: eu-west-3
    bucket-name:
      photos: bb-good-photos
      packages: barter-bay-app-packages
    key:
      secret: ${S3_SECRET}
      access: ${S3_SECRET}
