package com.barterbay.app.enumeration;

public enum Category {
  CONSTRUCTION_AND_DECORATION,
  FOOD,
  CHEMICAL_INDUSTRY,
  SOFT_DRINKS,
  ALCOHOLIC_DRINKS,
  OTHER_INDUSTRIAL_GOODS,
  EQUIPMENT_AND_EQUIPMENT,
  BEAUTY_AND_HEALTH
}
