# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# -------------------------------------------------
# Copyleft (c) by Paskar Oleksandr
# -------------------------------------------------

name: Java CI With Maven

env:
  APPLICATION_NAME: "BarterBay"
  PACKAGE_NAME: "deploy-version-${{ github.sha }}"

on:
  push:
    branches: [ development ]
  pull_request:
    branches:
      - '**' # matches every branch

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:

    - name: Git clone my repo
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build project with Maven
      run: mvn clean install -Dactive.profile=prod -DskipTests
